"""upd type user_id for channels table

Revision ID: a3e2f892a938
Revises: fedb609abe1b
Create Date: 2024-01-12 17:31:29.944251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e2f892a938'
down_revision: Union[str, None] = 'fedb609abe1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('m', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'm')
    # ### end Alembic commands ###
